{
 "title": "Kong (official)",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (https://github.com/yaoice/kong-plugin-prometheus/blob/0.6.0-add_request_count/grafana/kong-official.json)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kong_latency_bucket, job)"
   },
   {
    "name": "service",
    "query": "label_values(kong_http_status{job=~\"$job\"},service)"
   },
   {
    "name": "route",
    "query": "label_values(kong_http_status{job=~\"$job\"},route)"
   }
  ]
 },
 "panels": [
  { "title": "Request count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request count per route/service ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum(increase(kong_request_count{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[24h])) by (service))",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "floor(sum(increase(kong_request_count{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[24h])) by (route))",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Request count per route/service by status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(increase(kong_request_count{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[24h]))",
     "legendFormat": "service:{{service}}-{{code}}"
    },
    {
     "expr": "floor(increase(kong_request_count{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[24h]))",
     "legendFormat": "route:{{route}}-{{code}}"
    }
   ]
  },
  { "title": "Request rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total requests per second (RPS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_status{job=~\"$job\"}[5m]))",
     "legendFormat": "Requests/second"
    }
   ]
  },
  {
   "title": "RPS per route/service ($service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_status{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[5m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(kong_http_status{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[5m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "RPS per route/service by status code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_status{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[5m])) by (service,code)",
     "legendFormat": "service:{{service}}-{{code}}"
    },
    {
     "expr": "sum(rate(kong_http_status{job=~\"$job\", service=~\"$service\", route=~\"$route\"}[5m])) by (route,code)",
     "legendFormat": "route:{{route}}-{{code}}"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Kong Proxy Latency across all services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"kong\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"kong\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"kong\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"kong\", service =~ \"$service\",route=~\"$route\"}[5m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"kong\", service =~ \"$service\",route=~\"$route\"}[5m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"kong\", service =~ \"$service\",route=~\"$route\"}[5m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"kong\", service =~ \"$service\",route=~\"$route\"}[5m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"kong\", service =~ \"$service\",route=~\"$route\"}[5m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"kong\", service =~ \"$service\",route=~\"$route\"}[5m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Request Time across all services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"request\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"request\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"request\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Time per service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"request\", service =~ \"$service\",route=~\"$route\"}[5m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"request\", service =~ \"$service\",route=~\"$route\"}[5m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"request\", service =~ \"$service\",route=~\"$route\"}[5m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Request Time per Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"request\", service =~ \"$service\",route=~\"$route\"}[5m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"request\", service =~ \"$service\",route=~\"$route\"}[5m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"request\", service =~ \"$service\",route=~\"$route\"}[5m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Upstream time across all services",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"upstream\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"upstream\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"upstream\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Upstream Time across per service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"upstream\", service =~ \"$service\",route=~\"$route\"}[5m])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"upstream\", service =~ \"$service\",route=~\"$route\"}[5m])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"upstream\", service =~ \"$service\",route=~\"$route\"}[5m])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Time across per Route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"upstream\", service =~ \"$service\",route=~\"$route\"}[5m])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"upstream\", service =~ \"$service\",route=~\"$route\"}[5m])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_bucket{job=~\"$job\", type=\"upstream\", service =~ \"$service\",route=~\"$route\"}[5m])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth{job=~\"$job\"}[5m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth{job=~\"$job\", type=\"egress\", service =~\"$service\",route=~\"$route\"}[5m])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(irate(kong_bandwidth{job=~\"$job\", type=\"egress\", service =~\"$service\",route=~\"$route\"}[5m])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Ingress per service/route",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth{job=~\"$job\", type=\"ingress\", service =~\"$service\"}[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Kong memory usage by Node ($instance)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 75 },
   "repeat": "instance",
   "targets": [
    {
     "expr": "(kong_memory_lua_shared_dict_bytes{job=~\"$job\"}/kong_memory_lua_shared_dict_total_bytes{job=~\"$job\"})*100",
     "legendFormat": "{{shared_dict}}"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx connection state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kong_nginx_http_current_connections{job=~\"$job\", state=~\"activ|reading|writing|waiting\"}[5m])) by (state)",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Total Connections",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kong_nginx_http_current_connections{job=~\"$job\", state=\"total\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Handled Connections",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kong_nginx_http_current_connections{job=~\"$job\", state=\"handled\"})",
       "legendFormat": "Handled"
      }
     ]
    },
    {
     "title": "Accepted Connections",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kong_nginx_http_current_connections{job=~\"$job\", state=\"accepted\"})",
       "legendFormat": "Accepted"
      }
     ]
    }
   ]
  }
 ]
}